### ISSUE TITLE
colorChange event does not run when you change the color in the picker

### ISSUE THREAD

**Issue by lewis45454** [R-TEK/colr_pickr#6]
**Details**
What browser were you using: Chrome
What OS were you using: Windows
Project version you have: Latest (cdn)

**Describe the bug**
colorChange event does not run when you change the color in the picker, only when you exit it.

**To Reproduce**
1. Open the picker
2. Change the color
4. See error, it doesn't run the event

If this isn't a bug and it's meant to do this, would you be able to make a separate event for when you change the color on the picker.

**Comment by R-TEK** [comment]
Could you send me the error you were getting please, I don't seem to be getting the error on my side when following your reproduce bug instructions.

A guess as to why you're getting an error may be because you call the CDN link in a script tag above all your other HTML, if so try moving the script tag to the very bottom of the <body> tag. Otherwise just send me the error message and I'll take a look.

Thanks

**Comment by R-TEK** [comment]
@lewis45454

**Comment by lewis45454** [comment]
It works if you click out of the picker, just not while you are choosing the color.

**Comment by R-TEK** [comment]
Oh, so you mean the color only updates your elements when you leave the picker and not while dragging around the color box and slider?

**Comment by R-TEK** [comment]
@lewis45454 If so then this supposed to be the case. The pickers is in the center of the screen with a darkened background I cant see much use in making the picker update while changing color.

When i next work on this I plan on making a widget that appears next to the button used to open it, I can see how it would be useful to update color event while changing color when in this case

**Comment by lewis45454** [comment]
That's correct, it's fine.
